# Site settings
title: tapir
email: tapir@bmiag.de
description: >
  tapir - Test API against Regression

baseurl: "/tapir-website" # the subpath of your site, e.g. /blog/
url: https://tapir-test.github.io # the base hostname & protocol for your site
twitter:
    username: tapir_test

author: olibutzki


logo: /img/tapir-icon-circle.png
image: /img/tapir-icon-circle.png

social:
    name: tapir
    links:
        - https://twitter.com/tapir_test

repository     : "tapir-test/tapir-website"
staticmanUrl: https://api.staticman.net/v2/entry/tapir-test/tapir-website/master/comments
git_address: https://github.com/tapir-test/tapir-website
git_edit_address: https://github.com/tapir-test/tapir-website/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: tapir

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: ""
  values:
    image: /img/tapir-icon-circle.png
    seo:
      type: "WebPage"
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog
    seo:
        type: "BlogPosting"

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs


collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

staticman:
  branch                 : "master"

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LcRtz8UAAAAAA4jcY72sd_LOI7bmUJVQh_8wxIb"
  secret: "TC88Ah6QZbIX+9I9kdH9fl60+4x9ypFuiHF33KvzWvVUUygFe0Ium9SZSSjx+6wVS400Mo3OH2NNjZvh82Fe4W2rVRDtCiXecvMC3cHP/NVwNZLI+9PEODATtGydsdvcMAixwKdI+svFwz0GvQYe8oxEGfTJkcsUxvANLbjiFl4="
